---
title: "Match hyper, geno, pheno"
author: "yebi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Library/CloudStorage/OneDrive-VirginiaTech/Research/Codes/research/RiceUNLHyperspec/Geno/codes")
path = "/Users/yebi/Library/CloudStorage/OneDrive-VirginiaTech/Research/Codes/research/RiceUNLHyperspec/GWAS"
```

## loading pacakges.

```{r}
library(lme4)
library(tidyverse)
library(readxl)
```

## Read in pheno data --- Hyperspectral data.

```{r, eval = F}
hyp_control <- read_excel("../../Hyperspec/Big_HNT2018_Hyperspec_Data_TG_PP_v6.xlsx", sheet = 1)
hyp_stress <- read_excel("../../Hyperspec/Big_HNT2018_Hyperspec_Data_TG_PP_v6.xlsx", sheet = 2)

hyp_control$NSFTV_Id <- paste0("NSFTV_", hyp_control$NSFTV_Id)
hyp_stress$NSFTV_Id <- paste0("NSFTV_", hyp_stress$NSFTV_Id)

colnames(hyp_control)[-c(1:2)] <- paste0("hyp_", colnames(hyp_control)[-c(1:2)])
colnames(hyp_stress)[-c(1:2)] <- paste0("hyp_", colnames(hyp_stress)[-c(1:2)])

dup.ix = duplicated(hyp_control$NSFTV_Id)
hyp_control = hyp_control[!dup.ix, ] #remove one duplicated NSFTV.Id

table(hyp_control$NSFTV_Id %in% hyp_stress$NSFTV_Id)
table(hyp_stress$NSFTV_Id %in% hyp_control$NSFTV_Id)
```

## Read in geno and map data.

```{r, eval = F}
geno_700k <- readRDS("../geno_final_700K.rds")
map_700k <- readRDS("../mapinfo_final_700k.rds")
map_700k = map_700k[,c(2,1,4)]
colnames(map_700k) = c("SNPName","Chromosome","Position")
colnames(geno_700k) = map_700k$SNPName
```

### Control --- hpy v.s. geno

```{r, eval = F}
hyp_control = hyp_control[hyp_control$NSFTV_Id %in% rownames(geno_700k), ] # 223*242
geno_control = geno_700k[rownames(geno_700k) %in% hyp_control$NSFTV_Id, ] # 223*411066
geno_control = geno_control[match(hyp_control$NSFTV_Id, rownames(geno_control)), ]

p_control <- colMeans(geno_control)/2
maf_control <- ifelse(p_control > 0.5, 1-p_control, p_control)
maf_control.index <- which(maf_control < 0.05) 
geno_control <- geno_control[,-maf_control.index] #223 391936
map_control <- map_700k[-maf_control.index, ] #391936      3

table(rownames(geno_control) == hyp_control$NSFTV_Id)
table(colnames(geno_control) == map_control$SNPName)
```

### Stress -- hyp v.s. geno

```{r, eval = F}
hyp_stress = hyp_stress[hyp_stress$NSFTV_Id %in% rownames(geno_700k), ] # 223*242
geno_stress = geno_700k[rownames(geno_700k) %in% hyp_stress$NSFTV_Id, ] # 215*411066
geno_stress = geno_stress[match(hyp_stress$NSFTV_Id, rownames(geno_stress)), ]

p_stress <- colMeans(geno_stress)/2
maf_stress <- ifelse(p_stress > 0.5, 1-p_stress, p_stress)
maf_stress.index <- which(maf_stress < 0.05) 
geno_stress <- geno_stress[,-maf_stress.index] #215 390232
map_stress <- map_700k[-maf_stress.index, ] #390232      3

table(rownames(geno_stress) == hyp_stress$NSFTV_Id)
table(colnames(geno_stress) == map_stress$SNPName)
```

```{r}
save(geno_control, geno_stress, file=file.path(path,"geno.rr.RData"))
save(hyp_control, hyp_stress, file = file.path(path, "hyp.rr.Rdata"))
save(map_control, map_stress, file = file.path(path, "map.rr.Rdata"))
```

### GWAS data frame
```{r, echo = TRUE, eval = FALSE}
W_stress <- data.frame(marker = map_stress[,1], 
                        chrom = map_stress[,2], 
                        pos = map_stress[,3], 
                        t(geno_stress-1), 
                        check.names = FALSE) #389962    192

W_control <- data.frame(marker = map_control[,1], 
                        chrom = map_control[,2], 
                        pos = map_control[,3], 
                        t(geno_control-1), 
                        check.names = FALSE) #385276    196
```

```{r}
save(W_control, file=file.path(path,"W_stress.RData"))
save(W_stress, file=file.path(path,"W_control.RData"))
```

######### old code for prediction

------------------------------------------------------------------------

## Read in trait data.

------------------------------------------------------------------------

```{r}
#Load all the traits data.
dfL <- list()
for (i in 1:4){
  dfL[[i]] <- read_excel("../../Trait/Big_HNT_average_replicates_PP.xlsx", sheet = i)
}




#control trait data
dfL_control <- list()
dfL_control[[1]]<-dfL[[1]]
dfL_control[[2]]<-dfL[[3]]
names(dfL_control) <- c("Fertility", "Morpho")




#stress trait data.
dfL_stress <- list()
dfL_stress[[1]]<-dfL[[2]]
dfL_stress[[2]]<-dfL[[4]]
names(dfL_stress) <- c("Fertility", "Morpho")



#remove NA
dfL = lapply(dfL, na.omit) 

for(i in 1:4){
  dfL[[i]]$NSFTV_Id=paste0("NSFTV_",dfL[[i]]$NSFTV_Id)
  # print(sum(duplicated(dfL[[i]]$NSFTV_Id))) #no duplicated ids.
}




#Don't do this 
#match all traits with same ID
# for(i in 1:8){
#   print(table(dfL[[i]]$NSFTV_Id %in% dfL$SGW_Stress$NSFTV_Id))
# }
# names_t=intersect(dfL$SGW_Control$NSFTV_Id, dfL$SGW_Stress$NSFTV_Id) #185


```

------------------------------------------------------------------------

## Prune geno, trait, hyp dataset.

------------------------------------------------------------------------

##geno

```{r}
# geno <- geno_700k[names_t_p_g, ] #171 411066
p <- colMeans(geno)/2
maf <- ifelse(p> 0.5, 1-p, p)
maf.index <- which(maf < 0.05) 
geno <- geno[,-maf.index] #171 384610
# save(geno, file = "../geno.rr.RData")
```

##trait

```{r}
dfL = lapply(dfL, function(x) x=x[x$NSFTV_Id%in%names_t_p_g, ])

for (i in c(1,3,5,7)){
  dfL[[i]]$Treatment = "Control"
  dfL[[i+1]]$Treatment = "Stress"
}


colnames(dfL$Fertility_Control)[3] <- "Fertility"
colnames(dfL$Fertility_Stress)[3] <- "Fertility"
Fertility <- rbind(dfL$Fertility_Control, dfL$Fertility_Stress)


Morpho <- rbind(dfL$Morpho_Control, dfL$Morpho_Stress)

colnames(dfL$SGW_Control)[3] <- "SGW"
colnames(dfL$SGW_Stress)[3] <- "SGW"
SGW <- rbind(dfL$SGW_Control, dfL$SGW_Stress)

Seed_Color <- rbind(dfL$Seed_Color_Control, dfL$Seed_Color_Stress)

traits_df <- merge(merge(merge(Fertility, Morpho), SGW), Seed_Color)
traits_df$NSFTV_Id <- as.factor(traits_df$NSFTV_Id)

save(traits_df, file="../../Trait/traits_df.RData")
```
